---
  - name: install php for nginx
    sudo: True
    action: apt pkg=$item state=latest
    with_items:
      - php5-common
      - php5-cli 
      - php5-fpm
      - php5-mysql

  - name: add nginx example vhost
    sudo: True
    action: template src=vhost.conf.j2 dest=/etc/nginx/sites-available/vhost-example.conf
    notify:
      - restart nginx

  - name: Make sure that directory exsists
    action: file path=$vhost_dir state=directory recurse=yes owner=$user

  - name: Copy site files
    action: template src=index.php.j2 dest=$vhost_dir/index.php

  - name: Make sure that directory exsists
    action: file path=$vhost_dir state=directory recurse=yes owner=$user

  - name: link nginx example vhost in sites-enabled
    action: file src=/etc/nginx/sites-available/vhost-example.conf dest=/etc/nginx/sites-enabled/vhost-example.conf state=link
    notify:
      - restart nginx
