---
# - name: Install db packages
#   sudo: True
#   action: apt pkg=$item state=latest 
#   with_items:
#     - postgresql-{{ pgsql_version }}
#     - libpq-dev
#     - python-psycopg2
# 
# - name: Ensure database is created
#   sudo: True
#   sudo_user: postgres
#   action: postgresql_db 
#           db={{ dbname }} 
#           encoding='UTF-8'
#           lc_collate='en_US.UTF-8'
#           lc_ctype='en_US.UTF-8'
#           template='template0'
# 
# - name: Ensure user has access to database
#   sudo: True
#   sudo_user: postgres
#   action: postgresql_user 
#           db={{ dbname }} 
#           user={{ dbuser }} 
#           password={{ dbpass }} 
#           priv=ALL
# 
# - name: Ensure user does not have unnecessary privilege
#   sudo: True
#   sudo_user: postgres
#   action: postgresql_user 
#           user={{ dbuser }} 
#           role_attr_flags=NOSUPERUSER,NOCREATEDB 
# 
- name: Install db packages
  sudo: True
  action: apt pkg=$item state=latest 
  with_items:
    - python-mysqldb
    - mysql-server

- name: mysql config file that binds to all interfaces
  copy: src=my.cnf dest=/etc/mysql/my.cnf owner=root group=root mode=0644
  notify: restart mysql

- mysql_db: name={{ dbname }} state=present

- name: Configure the root credentials
  mysql_user: name={{ dbuser }} password={{ dbpass }} host="%" priv=*.*:ALL state=present
